swagger: '2.0'
info:
  version: '1.0.0'
  title: Zegen
schemes: [http]
consumes: [application/json, multipart/form-data]
produces: [application/json]
securityDefinitions:
  authorization:
    type: apiKey
    in: header
    name: Authorization

paths:
  # health
  /health:
    $ref: ./path/v1/health/health.yml

  # authentication
  /v1/register:
    $ref: ./path/v1/authentication/register.yml

  /v1/login:
    $ref: ./path/v1/authentication/login.yml

  # user
  # /v1/profile:
    # $ref: ./path/v1/user/profile.yml

  # author
  /v1/author:
    $ref: ./path/v1/author/author.yml

  /v1/author/{author_id}:
    $ref: ./path/v1/author/author.id.yml

definitions:
  Principal:
    type: object
    properties:
      username:
        type: string
      user_id:
        type: number
        format: uint64
      expired_at:
        type: string
        format: date-time

  User:
    allOf:
      - $ref: "./definitions/common.yml#/definitions/ModelIdentifier"
      - $ref: "./definitions/common.yml#/definitions/ModelTrackTime"
      - $ref: "./definitions/user.yml#/definitions/UserData"

  Author:
    allOf:
    - $ref: "./definitions/common.yml#/definitions/ModelIdentifier"
    - $ref: "./definitions/common.yml#/definitions/ModelTrackTime"
    - $ref: ./definitions/author.yml#/definitions/AuthorData
    - $ref: ./definitions/author.yml#/definitions/AuthorForeignKey

  Book:
    allOf:
    - $ref: "./definitions/common.yml#/definitions/ModelIdentifier"
    - $ref: "./definitions/common.yml#/definitions/ModelTrackTime"
    - $ref: ./definitions/book.yml#/definitions/BookData
    - $ref: ./definitions/book.yml#/definitions/BookForeignKey
