consumes:
    - application/json
    - multipart/form-data
produces:
    - application/json
schemes:
    - http
swagger: "2.0"
info:
    title: Zegen
    version: 1.0.0
paths:
    /health:
        get:
            responses:
                default:
                    schema:
                        $ref: '#/definitions/error'
                    description: Server Error
                "200":
                    schema:
                        $ref: '#/definitions/success'
                    description: Health Check
            security: []
            description: Check if the App is Running
            tags:
                - health
            summary: Health Check
            operationId: health
    /v1/author:
        post:
            tags:
                - author
            summary: Create
            operationId: createAuthor
            parameters:
                - name: data
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/createAuthorParamsBody'
            responses:
                "201":
                    description: Success create
                    schema:
                        $ref: '#/definitions/successCreateAuthor'
                default:
                    schema:
                        $ref: '#/definitions/error'
                    description: Server Error
            security:
                - authorization: []
            description: Create author
    /v1/author/{author_id}:
        put:
            security:
                - authorization: []
            description: Update author
            tags:
                - author
            summary: Update
            operationId: updateAuthor
            parameters:
                - format: uint64
                  name: author_id
                  in: path
                  required: true
                  type: integer
                - name: data
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/updateAuthorParamsBody'
            responses:
                "200":
                    description: Success update
                    schema:
                        $ref: '#/definitions/success'
                default:
                    description: Server Error
                    schema:
                        $ref: '#/definitions/error'
        delete:
            parameters:
                - type: integer
                  format: uint64
                  name: author_id
                  in: path
                  required: true
            responses:
                "200":
                    description: Success delete
                    schema:
                        $ref: '#/definitions/success'
                default:
                    description: Server Error
                    schema:
                        $ref: '#/definitions/error'
            security:
                - authorization: []
            description: Soft delete author
            tags:
                - author
            summary: Soft Delete
            operationId: softDeleteAuthor
    /v1/book:
        post:
            parameters:
                - name: data
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/createBookParamsBody'
            responses:
                "201":
                    description: Success create
                    schema:
                        $ref: '#/definitions/successCreateBook'
                default:
                    description: Server Error
                    schema:
                        $ref: '#/definitions/error'
            security:
                - authorization: []
            description: Create book
            tags:
                - book
            summary: Create
            operationId: createBook
    /v1/book/{book_id}:
        delete:
            security:
                - authorization: []
            description: Soft delete book
            tags:
                - book
            summary: Soft Delete
            operationId: softDeleteBook
            parameters:
                - type: integer
                  format: uint64
                  name: book_id
                  in: path
                  required: true
            responses:
                "200":
                    description: Success delete
                    schema:
                        $ref: '#/definitions/success'
                default:
                    description: Server Error
                    schema:
                        $ref: '#/definitions/error'
        put:
            security:
                - authorization: []
            description: Update book
            tags:
                - book
            summary: Update
            operationId: updateBook
            parameters:
                - in: path
                  required: true
                  type: integer
                  format: uint64
                  name: book_id
                - name: data
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/updateBookParamsBody'
            responses:
                default:
                    description: Server Error
                    schema:
                        $ref: '#/definitions/error'
                "200":
                    description: Success update
                    schema:
                        $ref: '#/definitions/success'
    /v1/login:
        post:
            responses:
                "200":
                    description: Success login
                    schema:
                        $ref: '#/definitions/successLogin'
                    headers:
                        token:
                            type: string
                default:
                    description: Server Error
                    schema:
                        $ref: '#/definitions/error'
            security: []
            description: Login
            tags:
                - authentication
            summary: Login
            operationId: login
            parameters:
                - name: data
                  in: body
                  schema:
                    $ref: '#/definitions/loginParamsBody'
    /v1/register:
        post:
            responses:
                "201":
                    description: Success register
                    schema:
                        $ref: '#/definitions/successRegister'
                default:
                    description: Server Error
                    schema:
                        $ref: '#/definitions/error'
            security: []
            description: Register user
            tags:
                - authentication
            summary: Register
            operationId: register
            parameters:
                - name: data
                  in: body
                  schema:
                    $ref: '#/definitions/registerParamsBody'
definitions:
    Principal:
        type: object
        properties:
            expired_at:
                format: date-time
                type: string
            user_id:
                type: number
                format: uint64
            username:
                type: string
    success:
        type: object
        properties:
            message:
                type: string
    successCreateAuthor:
        allOf:
            - $ref: '#/definitions/success'
            - $ref: '#/definitions/successCreateAuthorAllOf1'
    successCreateBook:
        allOf:
            - $ref: '#/definitions/success'
            - $ref: '#/definitions/successCreateBookAllOf1'
    Book:
        allOf:
            - $ref: '#/definitions/modelIdentifier'
            - $ref: '#/definitions/modelTrackTime'
            - $ref: '#/definitions/bookData'
            - $ref: '#/definitions/bookForeignKey'
    authorForeignKey:
        properties:
            books:
                type: array
                items:
                    $ref: '#/definitions/bookAuthor'
        type: object
    modelIdentifier:
        type: object
        required:
            - id
        properties:
            id:
                type: integer
                format: uint64
    updateAuthorParamsBody:
        type: object
        required:
            - name
            - country
        properties:
            country:
                type: string
                minLength: !!float 1
            name:
                type: string
                minLength: !!float 1
        x-go-gen-location: operations
    User:
        allOf:
            - $ref: '#/definitions/modelIdentifier'
            - $ref: '#/definitions/modelTrackTime'
            - $ref: '#/definitions/userData'
    bookAuthor:
        allOf:
            - $ref: '#/definitions/modelIdentifier'
            - $ref: '#/definitions/modelTrackTime'
            - $ref: '#/definitions/bookAuthorData'
    bookForeignKey:
        type: object
        properties:
            authors:
                type: array
                items:
                    $ref: '#/definitions/bookAuthor'
    successRegisterAllOf1:
        type: object
        properties:
            user_id:
                format: uint64
                type: number
        x-go-gen-location: models
    Author:
        allOf:
            - $ref: '#/definitions/modelIdentifier'
            - $ref: '#/definitions/modelTrackTime'
            - $ref: '#/definitions/authorData'
            - $ref: '#/definitions/authorForeignKey'
    error:
        type: object
        properties:
            code:
                type: integer
            message:
                type: string
                example: error
    loginParamsBody:
        type: object
        required:
            - username
            - password
        properties:
            password:
                type: string
            username:
                type: string
        x-go-gen-location: operations
    successRegister:
        allOf:
            - $ref: '#/definitions/success'
            - $ref: '#/definitions/successRegisterAllOf1'
    bookAuthorData:
        properties:
            author_id:
                type: string
            book_id:
                type: string
        type: object
    createBookParamsBody:
        type: object
        required:
            - title
            - isbn
            - published_year
            - author_ids
        properties:
            author_ids:
                type: array
                items:
                    type: number
                    minItems: !!float 1
                    uniqueItems: true
            isbn:
                type: string
                minLength: !!float 1
            published_year:
                type: number
                format: int64
            title:
                minLength: !!float 1
                type: string
        x-go-gen-location: operations
    modelTrackTime:
        type: object
        properties:
            created_at:
                x-omitempty: false
                type: string
                format: date-time
                x-go-custom-tag: gorm:"column:created_at"
                x-nullable: true
            deleted_at:
                type: string
                format: date-time
                x-go-custom-tag: gorm:"column:deleted_at"
                x-nullable: true
                x-omitempty: false
            updated_at:
                x-nullable: true
                x-omitempty: false
                type: string
                format: date-time
                x-go-custom-tag: gorm:"column:updated_at"
    successLogin:
        allOf:
            - $ref: '#/definitions/success'
            - $ref: '#/definitions/successLoginAllOf1'
    updateBookParamsBody:
        x-go-gen-location: operations
        type: object
        required:
            - title
            - isbn
            - published_year
            - author_ids
        properties:
            author_ids:
                type: array
                items:
                    type: number
                    minItems: !!float 1
                    uniqueItems: true
            isbn:
                type: string
                minLength: !!float 1
            published_year:
                type: number
                format: int64
            title:
                type: string
                minLength: !!float 1
    userData:
        type: object
        properties:
            password:
                type: string
                x-omitempty: false
            username:
                x-omitempty: false
                type: string
    bookData:
        type: object
        properties:
            publishedYear:
                type: number
                format: int64
            title:
                type: string
            isbn:
                type: string
    registerParamsBody:
        required:
            - username
            - password
        properties:
            password:
                minLength: !!float 8
                type: string
            username:
                type: string
        x-go-gen-location: operations
        type: object
    successCreateAuthorAllOf1:
        type: object
        properties:
            author_id:
                type: number
                format: uint64
        x-go-gen-location: models
    successLoginAllOf1:
        properties:
            expired_at:
                type: string
        x-go-gen-location: models
        type: object
    authorData:
        type: object
        properties:
            country:
                type: string
            name:
                type: string
    successCreateBookAllOf1:
        type: object
        properties:
            book_id:
                format: uint64
                type: number
        x-go-gen-location: models
    createAuthorParamsBody:
        type: object
        required:
            - name
            - country
        properties:
            country:
                type: string
                minLength: !!float 1
            name:
                type: string
                minLength: !!float 1
        x-go-gen-location: operations
securityDefinitions:
    authorization:
        type: apiKey
        name: Authorization
        in: header
