consumes:
    - application/json
    - multipart/form-data
produces:
    - application/json
schemes:
    - http
swagger: "2.0"
info:
    title: Zegen
    version: 1.0.0
paths:
    /v1/book:
        post:
            security:
                - authorization: []
            description: Create book
            tags:
                - book
            summary: Create
            operationId: createBook
            parameters:
                - name: data
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/createBookParamsBody'
            responses:
                "201":
                    description: Success create
                    schema:
                        $ref: '#/definitions/successCreateBook'
                default:
                    description: Server Error
                    schema:
                        $ref: '#/definitions/error'
    /v1/book/{book_id}:
        get:
            summary: Find One
            operationId: findOneBook
            parameters:
                - name: book_id
                  in: path
                  required: true
                  type: integer
                  format: uint64
            responses:
                default:
                    description: Server Error
                    schema:
                        $ref: '#/definitions/error'
                "200":
                    schema:
                        $ref: '#/definitions/successFindOneBook'
                    description: Success find data
            description: Find one book
            tags:
                - book
        put:
            description: Update book
            tags:
                - book
            summary: Update
            operationId: updateBook
            parameters:
                - name: book_id
                  in: path
                  required: true
                  type: integer
                  format: uint64
                - name: data
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/updateBookParamsBody'
            responses:
                "200":
                    description: Success update
                    schema:
                        $ref: '#/definitions/success'
                default:
                    description: Server Error
                    schema:
                        $ref: '#/definitions/error'
            security:
                - authorization: []
        delete:
            security:
                - authorization: []
            description: Soft delete book
            tags:
                - book
            summary: Soft Delete
            operationId: softDeleteBook
            parameters:
                - in: path
                  required: true
                  type: integer
                  format: uint64
                  name: book_id
            responses:
                "200":
                    description: Success delete
                    schema:
                        $ref: '#/definitions/success'
                default:
                    description: Server Error
                    schema:
                        $ref: '#/definitions/error'
    /v1/login:
        post:
            parameters:
                - name: data
                  in: body
                  schema:
                    $ref: '#/definitions/loginParamsBody'
            responses:
                "200":
                    description: Success login
                    schema:
                        $ref: '#/definitions/successLogin'
                    headers:
                        token:
                            type: string
                default:
                    description: Server Error
                    schema:
                        $ref: '#/definitions/error'
            security: []
            description: Login
            tags:
                - authentication
            summary: Login
            operationId: login
    /v1/register:
        post:
            tags:
                - authentication
            summary: Register
            operationId: register
            parameters:
                - name: data
                  in: body
                  schema:
                    $ref: '#/definitions/registerParamsBody'
            responses:
                default:
                    description: Server Error
                    schema:
                        $ref: '#/definitions/error'
                "201":
                    description: Success register
                    schema:
                        $ref: '#/definitions/successRegister'
            security: []
            description: Register user
    /health:
        get:
            description: Check if the App is Running
            tags:
                - health
            summary: Health Check
            operationId: health
            responses:
                "200":
                    description: Health Check
                    schema:
                        $ref: '#/definitions/success'
                default:
                    description: Server Error
                    schema:
                        $ref: '#/definitions/error'
            security: []
    /v1/author:
        post:
            description: Create author
            tags:
                - author
            summary: Create
            operationId: createAuthor
            parameters:
                - name: data
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/createAuthorParamsBody'
            responses:
                "201":
                    description: Success create
                    schema:
                        $ref: '#/definitions/successCreateAuthor'
                default:
                    description: Server Error
                    schema:
                        $ref: '#/definitions/error'
            security:
                - authorization: []
    /v1/author/{author_id}:
        put:
            parameters:
                - type: integer
                  format: uint64
                  name: author_id
                  in: path
                  required: true
                - required: true
                  schema:
                    $ref: '#/definitions/updateAuthorParamsBody'
                  name: data
                  in: body
            responses:
                "200":
                    description: Success update
                    schema:
                        $ref: '#/definitions/success'
                default:
                    description: Server Error
                    schema:
                        $ref: '#/definitions/error'
            security:
                - authorization: []
            description: Update author
            tags:
                - author
            summary: Update
            operationId: updateAuthor
        delete:
            security:
                - authorization: []
            description: Soft delete author
            tags:
                - author
            summary: Soft Delete
            operationId: softDeleteAuthor
            parameters:
                - format: uint64
                  name: author_id
                  in: path
                  required: true
                  type: integer
            responses:
                "200":
                    description: Success delete
                    schema:
                        $ref: '#/definitions/success'
                default:
                    description: Server Error
                    schema:
                        $ref: '#/definitions/error'
        get:
            responses:
                "200":
                    description: Success find data
                    schema:
                        $ref: '#/definitions/successFindOneAuthor'
                default:
                    description: Server Error
                    schema:
                        $ref: '#/definitions/error'
            description: Find one author
            tags:
                - author
            summary: Find One
            operationId: findOneAuthor
            parameters:
                - type: integer
                  format: uint64
                  name: author_id
                  in: path
                  required: true
definitions:
    successFindOneBookAllOf1DataAllOf3:
        type: object
        properties:
            authors:
                type: array
                items:
                    $ref: '#/definitions/successFindOneBookAllOf1DataAllOf3AuthorsItems'
        x-go-gen-location: models
    successLoginAllOf1:
        type: object
        properties:
            expired_at:
                type: string
        x-go-gen-location: models
    bookAuthorForeignKeyAuthor:
        allOf:
            - $ref: '#/definitions/modelIdentifier'
            - $ref: '#/definitions/modelTrackTime'
            - $ref: '#/definitions/authorData'
            - $ref: '#/definitions/authorForeignKey'
        x-go-gen-location: models
    createBookParamsBody:
        properties:
            author_ids:
                type: array
                items:
                    type: number
                    format: uint64
                    minItems: !!float 1
                    uniqueItems: true
            isbn:
                type: string
                minLength: !!float 1
            published_year:
                type: number
                format: int64
            title:
                type: string
                minLength: !!float 1
        x-go-gen-location: operations
        type: object
        required:
            - title
            - isbn
            - published_year
            - author_ids
    successCreateAuthorAllOf1:
        x-go-gen-location: models
        type: object
        properties:
            author_id:
                type: number
                format: uint64
    successFindOneAuthorAllOf1Data:
        allOf:
            - $ref: '#/definitions/modelIdentifier'
            - $ref: '#/definitions/authorData'
            - $ref: '#/definitions/modelTrackTime'
        x-go-gen-location: models
    successFindOneBook:
        allOf:
            - $ref: '#/definitions/success'
            - $ref: '#/definitions/successFindOneBookAllOf1'
    updateAuthorParamsBody:
        type: object
        required:
            - name
            - country
        properties:
            country:
                type: string
                minLength: !!float 1
            name:
                type: string
                minLength: !!float 1
        x-go-gen-location: operations
    error:
        type: object
        properties:
            code:
                type: integer
            message:
                type: string
                example: error
    modelIdentifier:
        type: object
        required:
            - id
        properties:
            id:
                format: uint64
                type: integer
    successFindOneBookAllOf1:
        type: object
        properties:
            data:
                $ref: '#/definitions/successFindOneBookAllOf1Data'
        x-go-gen-location: models
    successFindOneBookAllOf1DataAllOf3AuthorsItems:
        allOf:
            - $ref: '#/definitions/modelIdentifier'
            - $ref: '#/definitions/authorData'
        x-go-gen-location: models
    successRegister:
        allOf:
            - $ref: '#/definitions/success'
            - $ref: '#/definitions/successRegisterAllOf1'
    successFindOneBookAllOf1Data:
        allOf:
            - $ref: '#/definitions/modelIdentifier'
            - $ref: '#/definitions/bookData'
            - $ref: '#/definitions/modelTrackTime'
            - $ref: '#/definitions/successFindOneBookAllOf1DataAllOf3'
        x-go-gen-location: models
    Author:
        allOf:
            - $ref: '#/definitions/modelIdentifier'
            - $ref: '#/definitions/modelTrackTime'
            - $ref: '#/definitions/authorData'
            - $ref: '#/definitions/authorForeignKey'
    bookAuthorData:
        type: object
        properties:
            author_id:
                type: number
                format: uint64
            book_id:
                type: number
                format: uint64
    registerParamsBody:
        required:
            - username
            - password
        properties:
            password:
                type: string
                minLength: !!float 8
            username:
                type: string
        x-go-gen-location: operations
        type: object
    successCreateAuthor:
        allOf:
            - $ref: '#/definitions/success'
            - $ref: '#/definitions/successCreateAuthorAllOf1'
    successFindOneAuthor:
        allOf:
            - $ref: '#/definitions/success'
            - $ref: '#/definitions/successFindOneAuthorAllOf1'
    Principal:
        type: object
        properties:
            expired_at:
                type: string
                format: date-time
            user_id:
                type: number
                format: uint64
            username:
                type: string
    bookData:
        type: object
        properties:
            isbn:
                type: string
            publishedYear:
                type: number
                format: int64
            title:
                type: string
    successCreateBookAllOf1:
        x-go-gen-location: models
        type: object
        properties:
            book_id:
                type: number
                format: uint64
    successFindOneAuthorAllOf1:
        type: object
        properties:
            data:
                $ref: '#/definitions/successFindOneAuthorAllOf1Data'
        x-go-gen-location: models
    userData:
        type: object
        properties:
            password:
                type: string
                x-omitempty: false
            username:
                type: string
                x-omitempty: false
    bookAuthorForeignKeyBook:
        allOf:
            - $ref: '#/definitions/modelIdentifier'
            - $ref: '#/definitions/modelTrackTime'
            - $ref: '#/definitions/bookData'
            - $ref: '#/definitions/bookForeignKey'
        x-go-gen-location: models
    createAuthorParamsBody:
        required:
            - name
            - country
        properties:
            country:
                type: string
                minLength: !!float 1
            name:
                type: string
                minLength: !!float 1
        x-go-gen-location: operations
        type: object
    loginParamsBody:
        x-go-gen-location: operations
        type: object
        required:
            - username
            - password
        properties:
            password:
                type: string
            username:
                type: string
    success:
        type: object
        properties:
            message:
                type: string
    successRegisterAllOf1:
        x-go-gen-location: models
        type: object
        properties:
            user_id:
                format: uint64
                type: number
    authorData:
        type: object
        properties:
            name:
                type: string
            country:
                type: string
    bookAuthor:
        allOf:
            - $ref: '#/definitions/modelIdentifier'
            - $ref: '#/definitions/modelTrackTime'
            - $ref: '#/definitions/bookAuthorData'
            - $ref: '#/definitions/bookAuthorForeignKey'
    bookAuthorForeignKey:
        type: object
        properties:
            author:
                $ref: '#/definitions/bookAuthorForeignKeyAuthor'
            book:
                $ref: '#/definitions/bookAuthorForeignKeyBook'
    modelTrackTime:
        type: object
        properties:
            created_at:
                x-omitempty: false
                type: string
                format: date-time
                x-go-custom-tag: gorm:"column:created_at"
                x-nullable: true
            deleted_at:
                type: string
                format: date-time
                x-go-custom-tag: gorm:"column:deleted_at"
                x-nullable: true
                x-omitempty: false
            updated_at:
                type: string
                format: date-time
                x-go-custom-tag: gorm:"column:updated_at"
                x-nullable: true
                x-omitempty: false
    successCreateBook:
        allOf:
            - $ref: '#/definitions/success'
            - $ref: '#/definitions/successCreateBookAllOf1'
    successLogin:
        allOf:
            - $ref: '#/definitions/success'
            - $ref: '#/definitions/successLoginAllOf1'
    updateBookParamsBody:
        x-go-gen-location: operations
        type: object
        required:
            - title
            - isbn
            - published_year
            - author_ids
        properties:
            author_ids:
                type: array
                items:
                    format: uint64
                    minItems: !!float 1
                    uniqueItems: true
                    type: number
            isbn:
                type: string
                minLength: !!float 1
            published_year:
                type: number
                format: int64
            title:
                type: string
                minLength: !!float 1
    Book:
        allOf:
            - $ref: '#/definitions/modelIdentifier'
            - $ref: '#/definitions/modelTrackTime'
            - $ref: '#/definitions/bookData'
            - $ref: '#/definitions/bookForeignKey'
    User:
        allOf:
            - $ref: '#/definitions/modelIdentifier'
            - $ref: '#/definitions/modelTrackTime'
            - $ref: '#/definitions/userData'
    authorForeignKey:
        properties:
            books:
                type: array
                items:
                    $ref: '#/definitions/bookAuthor'
        type: object
    bookForeignKey:
        type: object
        properties:
            authors:
                type: array
                items:
                    $ref: '#/definitions/bookAuthor'
securityDefinitions:
    authorization:
        in: header
        type: apiKey
        name: Authorization
