consumes:
    - application/json
    - multipart/form-data
produces:
    - application/json
schemes:
    - http
swagger: "2.0"
info:
    title: Zegen
    version: 1.0.0
paths:
    /v1/author:
        post:
            responses:
                "201":
                    description: Success create
                    schema:
                        $ref: '#/definitions/successCreateAuthor'
                default:
                    description: Server Error
                    schema:
                        $ref: '#/definitions/error'
            security:
                - authorization: []
            description: Create author
            tags:
                - author
            summary: Create
            operationId: createAuthor
            parameters:
                - name: data
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/createAuthorParamsBody'
    /v1/login:
        post:
            parameters:
                - schema:
                    $ref: '#/definitions/loginParamsBody'
                  name: data
                  in: body
            responses:
                "200":
                    headers:
                        token:
                            type: string
                    description: Success login
                    schema:
                        $ref: '#/definitions/successLogin'
                default:
                    description: Server Error
                    schema:
                        $ref: '#/definitions/error'
            security: []
            description: Login
            tags:
                - authentication
            summary: Login
            operationId: login
    /v1/profile:
        get:
            security:
                - authorization: []
            description: Find my user data
            tags:
                - user
            summary: Find My User Data
            operationId: findMyUserData
            responses:
                "200":
                    description: Success fetch data
                    schema:
                        $ref: '#/definitions/myUserData'
                default:
                    description: Server Error
                    schema:
                        $ref: '#/definitions/error'
    /v1/register:
        post:
            description: Register user
            tags:
                - authentication
            summary: Register
            operationId: register
            parameters:
                - name: data
                  in: body
                  schema:
                    $ref: '#/definitions/registerParamsBody'
            responses:
                "201":
                    description: Success register
                    schema:
                        $ref: '#/definitions/successRegister'
                default:
                    schema:
                        $ref: '#/definitions/error'
                    description: Server Error
            security: []
    /health:
        get:
            responses:
                "200":
                    description: Health Check
                    schema:
                        $ref: '#/definitions/success'
                default:
                    description: Server Error
                    schema:
                        $ref: '#/definitions/error'
            security: []
            description: Check if the App is Running
            tags:
                - health
            summary: Health Check
            operationId: health
definitions:
    Author:
        allOf:
            - $ref: '#/definitions/modelIdentifier'
            - $ref: '#/definitions/modelTrackTime'
            - $ref: '#/definitions/authorData'
            - $ref: '#/definitions/authorForeignKey'
    Book:
        allOf:
            - $ref: '#/definitions/modelIdentifier'
            - $ref: '#/definitions/modelTrackTime'
            - $ref: '#/definitions/bookData'
            - $ref: '#/definitions/bookForeignKey'
    bookForeignKey:
        type: object
        properties:
            authors:
                type: array
                items:
                    $ref: '#/definitions/bookAuthor'
    success:
        type: object
        properties:
            message:
                type: string
    successCreateAuthorAllOf1:
        type: object
        properties:
            author_id:
                type: number
                format: uint64
        x-go-gen-location: models
    successRegister:
        allOf:
            - $ref: '#/definitions/success'
            - $ref: '#/definitions/successRegisterAllOf1'
    Principal:
        type: object
        properties:
            username:
                type: string
            expired_at:
                type: string
                format: date-time
            user_id:
                type: number
                format: uint64
    authorData:
        type: object
        properties:
            country:
                type: string
            name:
                type: string
    error:
        type: object
        properties:
            code:
                type: integer
            message:
                type: string
                example: error
    loginParamsBody:
        properties:
            password:
                type: string
            username:
                type: string
        x-go-gen-location: operations
        type: object
        required:
            - username
            - password
    successCreateAuthor:
        allOf:
            - $ref: '#/definitions/success'
            - $ref: '#/definitions/successCreateAuthorAllOf1'
    userData:
        type: object
        properties:
            password:
                type: string
                x-omitempty: false
            username:
                type: string
                x-omitempty: false
    User:
        allOf:
            - $ref: '#/definitions/modelIdentifier'
            - $ref: '#/definitions/modelTrackTime'
            - $ref: '#/definitions/userData'
    bookAuthor:
        allOf:
            - $ref: '#/definitions/modelIdentifier'
            - $ref: '#/definitions/modelTrackTime'
            - $ref: '#/definitions/bookAuthorData'
    createAuthorParamsBody:
        properties:
            country:
                type: string
                minLength: !!float 1
            name:
                type: string
                minLength: !!float 1
        x-go-gen-location: operations
        type: object
        required:
            - name
            - country
    modelIdentifier:
        type: object
        required:
            - id
        properties:
            id:
                type: integer
                format: uint64
    modelTrackTime:
        type: object
        properties:
            created_at:
                type: string
                format: date-time
                x-go-custom-tag: gorm:"column:created_at"
                x-nullable: true
                x-omitempty: false
            deleted_at:
                type: string
                format: date-time
                x-go-custom-tag: gorm:"column:deleted_at"
                x-nullable: true
                x-omitempty: false
            updated_at:
                x-go-custom-tag: gorm:"column:updated_at"
                x-nullable: true
                x-omitempty: false
                type: string
                format: date-time
    myUserData:
        type: object
        properties:
            username:
                x-omitempty: false
                type: string
    successLogin:
        allOf:
            - $ref: '#/definitions/success'
            - $ref: '#/definitions/successLoginAllOf1'
    authorForeignKey:
        type: object
        properties:
            books:
                type: array
                items:
                    $ref: '#/definitions/bookAuthor'
    bookAuthorData:
        type: object
        properties:
            author_id:
                type: string
            book_id:
                type: string
    bookData:
        type: object
        properties:
            isbn:
                type: string
            publishedYear:
                type: number
                format: int64
            title:
                type: string
    registerParamsBody:
        properties:
            password:
                type: string
                minLength: !!float 8
            username:
                type: string
        x-go-gen-location: operations
        type: object
        required:
            - username
            - password
    successLoginAllOf1:
        type: object
        properties:
            expired_at:
                type: string
        x-go-gen-location: models
    successRegisterAllOf1:
        type: object
        properties:
            user_id:
                type: number
                format: uint64
        x-go-gen-location: models
securityDefinitions:
    authorization:
        type: apiKey
        name: Authorization
        in: header
