consumes:
    - application/json
    - multipart/form-data
produces:
    - application/json
schemes:
    - http
swagger: "2.0"
info:
    title: Zegen
    version: 1.0.0
paths:
    /health:
        get:
            security: []
            description: Check if the App is Running
            tags:
                - health
            summary: Health Check
            operationId: health
            responses:
                "200":
                    description: Health Check
                    schema:
                        $ref: '#/definitions/success'
                default:
                    description: Server Error
                    schema:
                        $ref: '#/definitions/error'
    /v1/login:
        post:
            tags:
                - authentication
            summary: Login
            operationId: login
            parameters:
                - in: body
                  schema:
                    $ref: '#/definitions/loginParamsBody'
                  name: data
            responses:
                "201":
                    headers:
                        token:
                            type: string
                    description: Success login
                    schema:
                        $ref: '#/definitions/successLogin'
                default:
                    description: Server Error
                    schema:
                        $ref: '#/definitions/error'
            security: []
            description: Login
    /v1/profile:
        get:
            tags:
                - user
            summary: Find My User Data
            operationId: findMyUserData
            responses:
                "200":
                    description: Success fetch data
                    schema:
                        $ref: '#/definitions/myUserData'
                default:
                    schema:
                        $ref: '#/definitions/error'
                    description: Server Error
            security:
                - authorization: []
            description: Find my user data
    /v1/register:
        post:
            security: []
            description: Register user
            tags:
                - authentication
            summary: Register
            operationId: register
            parameters:
                - name: data
                  in: body
                  schema:
                    $ref: '#/definitions/registerParamsBody'
            responses:
                "200":
                    schema:
                        $ref: '#/definitions/successRegister'
                    description: Success register
                default:
                    description: Server Error
                    schema:
                        $ref: '#/definitions/error'
definitions:
    modelIdentifier:
        type: object
        required:
            - id
        properties:
            id:
                type: integer
                format: uint64
    successRegister:
        allOf:
            - $ref: '#/definitions/success'
            - $ref: '#/definitions/successRegisterAllOf1'
    modelTrackTime:
        type: object
        properties:
            created_at:
                x-nullable: true
                x-omitempty: false
                type: string
                format: date-time
                x-go-custom-tag: gorm:"column:created_at"
            deleted_at:
                x-go-custom-tag: gorm:"column:deleted_at"
                x-nullable: true
                x-omitempty: false
                type: string
                format: date-time
            updated_at:
                type: string
                format: date-time
                x-go-custom-tag: gorm:"column:updated_at"
                x-nullable: true
                x-omitempty: false
    success:
        type: object
        properties:
            message:
                type: string
    successLogin:
        allOf:
            - $ref: '#/definitions/success'
            - $ref: '#/definitions/successLoginAllOf1'
    error:
        type: object
        properties:
            code:
                type: integer
            message:
                type: string
                example: error
    myUserData:
        type: object
        properties:
            username:
                type: string
                x-omitempty: false
    principal:
        type: object
        properties:
            expired_at:
                type: string
                format: date-time
            user_id:
                type: number
                format: uint64
            username:
                type: string
    registerParamsBody:
        properties:
            password:
                minLength: !!float 8
                type: string
            username:
                type: string
        x-go-gen-location: operations
        type: object
        required:
            - username
            - password
    user:
        allOf:
            - $ref: '#/definitions/modelIdentifier'
            - $ref: '#/definitions/modelTrackTime'
            - $ref: '#/definitions/userData'
    userData:
        type: object
        properties:
            username:
                type: string
                x-omitempty: false
            password:
                type: string
                x-omitempty: false
    loginParamsBody:
        x-go-gen-location: operations
        type: object
        required:
            - username
            - password
        properties:
            password:
                type: string
            username:
                type: string
    successLoginAllOf1:
        type: object
        properties:
            expired_at:
                type: string
        x-go-gen-location: models
    successRegisterAllOf1:
        x-go-gen-location: models
        type: object
        properties:
            user_id:
                type: number
                format: uint64
securityDefinitions:
    authorization:
        type: apiKey
        name: Authorization
        in: header
